default:
  just --list

# Run the binary for a specific day's problems
run day part:
    cargo run -p day{{day}} --bin part{{part}}

# Run the test suite
test day="" part="":
    cargo nextest run {{ if day != "" { "-p day"+day } else { "" } }} {{part}}

# Create the crate for a day
create day:
    cargo generate --path ./template --name day{{day}}